/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAnalytics {
    }
    interface AppCrashes {
    }
    interface AppHome {
    }
    interface AppOther {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAnalyticsElement extends Components.AppAnalytics, HTMLStencilElement {
    }
    var HTMLAppAnalyticsElement: {
        prototype: HTMLAppAnalyticsElement;
        new (): HTMLAppAnalyticsElement;
    };
    interface HTMLAppCrashesElement extends Components.AppCrashes, HTMLStencilElement {
    }
    var HTMLAppCrashesElement: {
        prototype: HTMLAppCrashesElement;
        new (): HTMLAppCrashesElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppOtherElement extends Components.AppOther, HTMLStencilElement {
    }
    var HTMLAppOtherElement: {
        prototype: HTMLAppOtherElement;
        new (): HTMLAppOtherElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-analytics": HTMLAppAnalyticsElement;
        "app-crashes": HTMLAppCrashesElement;
        "app-home": HTMLAppHomeElement;
        "app-other": HTMLAppOtherElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAnalytics {
    }
    interface AppCrashes {
    }
    interface AppHome {
    }
    interface AppOther {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-analytics": AppAnalytics;
        "app-crashes": AppCrashes;
        "app-home": AppHome;
        "app-other": AppOther;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-analytics": LocalJSX.AppAnalytics & JSXBase.HTMLAttributes<HTMLAppAnalyticsElement>;
            "app-crashes": LocalJSX.AppCrashes & JSXBase.HTMLAttributes<HTMLAppCrashesElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-other": LocalJSX.AppOther & JSXBase.HTMLAttributes<HTMLAppOtherElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
