/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ErrorReportItem } from "./components/app-crashes/error-report-items-modal";
export namespace Components {
    interface AppAnalytics {
    }
    interface AppCrashes {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ErrorReportItemsModal {
        "items": ErrorReportItem[];
    }
}
declare global {
    interface HTMLAppAnalyticsElement extends Components.AppAnalytics, HTMLStencilElement {
    }
    var HTMLAppAnalyticsElement: {
        prototype: HTMLAppAnalyticsElement;
        new (): HTMLAppAnalyticsElement;
    };
    interface HTMLAppCrashesElement extends Components.AppCrashes, HTMLStencilElement {
    }
    var HTMLAppCrashesElement: {
        prototype: HTMLAppCrashesElement;
        new (): HTMLAppCrashesElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLErrorReportItemsModalElement extends Components.ErrorReportItemsModal, HTMLStencilElement {
    }
    var HTMLErrorReportItemsModalElement: {
        prototype: HTMLErrorReportItemsModalElement;
        new (): HTMLErrorReportItemsModalElement;
    };
    interface HTMLElementTagNameMap {
        "app-analytics": HTMLAppAnalyticsElement;
        "app-crashes": HTMLAppCrashesElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "error-report-items-modal": HTMLErrorReportItemsModalElement;
    }
}
declare namespace LocalJSX {
    interface AppAnalytics {
    }
    interface AppCrashes {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ErrorReportItemsModal {
        "items"?: ErrorReportItem[];
    }
    interface IntrinsicElements {
        "app-analytics": AppAnalytics;
        "app-crashes": AppCrashes;
        "app-home": AppHome;
        "app-root": AppRoot;
        "error-report-items-modal": ErrorReportItemsModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-analytics": LocalJSX.AppAnalytics & JSXBase.HTMLAttributes<HTMLAppAnalyticsElement>;
            "app-crashes": LocalJSX.AppCrashes & JSXBase.HTMLAttributes<HTMLAppCrashesElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "error-report-items-modal": LocalJSX.ErrorReportItemsModal & JSXBase.HTMLAttributes<HTMLErrorReportItemsModalElement>;
        }
    }
}
